[run]
init_cmds = [
	["go", "run", "main.go"]
]									# Commands run in start
watch_all = true					# Watch all sub-directories
watch_dirs = []						# Directories to watch
watch_exts = [".go"]				# Extensions to watch
ignore = [".git", "node_modules"] 	# Directories to exclude from watching
ignore_files = []					# Regexps for ignoring specific notifies
build_delay = 1500					# Minimal interval to Trigger build event
interrupt_timout = 1				# Time to wait until force kill
graceful_kill = true	# Wait for exit and before directly kill
cmds = [
	["go", "run", "main.go"]
]									# Commands to run
